name: JSON Documentation
on: [push]

jobs:
  validate:
    name: Engine Documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Update APT
        run: sudo apt update
      
      - name: Install LuaJIT and LuaRocks
        run: sudo apt install luajit luarocks

      - name: Install required Lua modules
        run: sudo luarocks install luafilesystem

      - name: Git checkout
        uses: actions/checkout@v1

      - name: Validate files structure
        run: luajit ./Lua_Scripts/ValidateFilesStructure.lua
      
      - name: Validate JSON files
        run: luajit ./Lua_Scripts/ValidateJSON.lua
      
      - name: Validate files content
        run: luajit ./Lua_Scripts/ValidateContent.lua

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Reformat JSON files
        run: |
          luajit ./Lua_Scripts/ReformatJSON.lua
          git add -A && git commit -m "Reformat JSON files" || true
      
      - name: Generate merged JSON files
        run: |
          luajit ./Lua_Scripts/GenerateMergedJSON.lua
          git add -A && git commit -m "Update Engine_Merged.json and Engine_Merged_Pretty.json" || true
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
