name: Documentation Verification
on: [push]

jobs:
  validate:
    name: Validation scripts
    runs-on: ubuntu-18.04
    steps:
      - name: Update APT
        run: sudo apt update
      
      - name: Install LuaJIT and LuaRocks
        run: sudo apt install luajit luarocks

      - name: Install required Lua modules
        run: sudo luarocks install luafilesystem

      - name: Git checkout
        uses: actions/checkout@v1

      - name: Validate files structure
        run: luajit ./Lua_Scripts/ValidateFilesStructure.lua
      
      - name: Validate JSON files
        run: luajit ./Lua_Scripts/ValidateJSON.lua
      
      - name: Validate files content
        run: luajit ./Lua_Scripts/ValidateContent.lua